### ISSUE TITLE
support for react-leaflet v1.0.0? 

### ISSUE THREAD

**Issue by smanousopoulos** [LiveBy/react-leaflet-choropleth#4]
Breaks with react-leaflet v1.0.0 due to rename of GeoJson to GeoJSON. Do you plan to support the new version?

I don't know if there are any more issues, I couldn't see anything else with a quick look: https://github.com/PaulLeCam/react-leaflet/releases/tag/v1.0.0

**Comment by jgimbel** [comment]
I knew this issue was coming since they changed it... I'll work on it tonight. Feel free to make a PR if you just can't wait

**Comment by jgimbel** [comment]
Fixed in version 2.0.0
