### ISSUE TITLE
TypeError: features.map is not a function

### ISSUE THREAD

**Issue by yanisneverlies** [LiveBy/react-leaflet-choropleth#7]
Hello. 
Recently I tried to use react-leaflet-choropleth and I've caught this error.

The code is exactly like in in Example.

import React, { Component } from 'react'
import Choropleth from 'react-leaflet-choropleth'
import { Map } from 'react-leaflet'
import { data } from './data'
import './App.css'

const style = {
    fillColor: '#F28F3B',
    weight: 2,
    opacity: 1,
    color: 'white',
    dashArray: '3',
    fillOpacity: 0.5
}

const App = (data) => (
  <div className="App">
    <Map>
      <Choropleth
        data={{type: 'FeatureCollection', features: data}}
        valueProperty={(feature) => feature.properties.value}
        scale={['#b3cde0', '#011f4b']}
        steps={7}
        mode='e'
        style={style}
        onEachFeature={(feature, layer) => layer.bindPopup(feature.properties.label)}
        ref={(el) => this.choropleth = el.leafletElement}
      />
    </Map>
  </div>
)

export default App

**Comment by AFRUITPIE** [comment]
I realize this is an old issue, but I believe the solution is that you need to pass specifically the features, not the entire geojson like shown in the README example.

So the code should look more like:

```
    <Choropleth
      data={{type: 'FeatureCollection', features: geojson.features}}
      ...
```

**Comment by jleape** [comment]
This solved the problem for me:

` <Choropleth
      data={geojson}`

**Comment by Gabriellavoura** [comment]
Same problem.
