### ISSUE TITLE
Is it compatible with React Leaflet V_2.0? I am having trouble using it.

### ISSUE THREAD

**Issue by fahshed** [LiveBy/react-leaflet-choropleth#9]

**Comment by gigincg** [comment]
Hey did you find any luck? I'm having the same issue. unable to get it to work in React Leaflet v2

**Comment by fahshed** [comment]
Nope. Couldn't use it with React leaflet V2.

But I found another way to make a choropleth map. Here's what I started with: [Mapping 'GeoJson Data' instead of 'Tiles'](https://medium.com/@eugenebelkovich/map-for-react-apps-with-leaflet-365f9df82d55)
Take a look at the last example.

**Comment by gigincg** [comment]
So I was able to use this package with React Leaflet V2. I'd love to make a PR with an example file, but I don't think the owner is active anymore
